# name: Bibletok CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   test-frontend:
#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         working-directory: frontend
    
#     strategy:
#       matrix:
#         node-version: [18.x]

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#         cache-dependency-path: 'frontend/package-lock.json'
#     - name: Install dependencies
#       run: npm ci
#     - name: Run lint
#       run: npm run lint
#     - name: Run tests
#       run: npm test
#     - name: Build
#       run: npm run build

#   test-backend:
#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         working-directory: server
    
#     strategy:
#       matrix:
#         node-version: [18.x]

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#         cache-dependency-path: 'server/package-lock.json'
#     - name: Install dependencies
#       run: npm ci
#     - name: Run tests
#       run: npm test
#     - name: Build
#       run: npm run build

#   deploy:
#     needs: [test-frontend, test-backend]
#     if: github.ref == 'refs/heads/main'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
      
#       # Deploy Frontend to Vercel
#       - name: Deploy Frontend to Vercel
#         uses: amondnet/vercel-action@v20
#         with:
#           vercel-token: ${{ secrets.VERCEL_TOKEN }}
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
#           vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
#           working-directory: ./frontend
          
#       # Deploy Backend to Vercel
#       - name: Deploy Backend to Vercel
#         uses: amondnet/vercel-action@v20
#         with:
#           vercel-token: ${{ secrets.VERCEL_TOKEN }}
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
#           vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}
#           working-directory: ./server